backend:
  name: github
  repo: YOUR_GITHUB_USERNAME/Kanchor
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blogs"
    folder: "content/blog"
    create: true

    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"

    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Thumbnail", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}